version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: feedback-system-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - feedback-network

volumes:
  postgres_data:

networks:
  feedback-network:
    driver: bridge